## Code 4.1 Differential Evolution

In [2]:
from scipy.optimize import differential_evolution
import numpy as np
import math

First Example

In [3]:
def f(x):
     return -np.exp(-(x - 10)**2)

In [4]:
bounds = [(-100,100)]

In [10]:
result = differential_evolution(f, bounds)
result.x, result.fun

(array([9.99999999]), array([-1.]))

Second Example - McCormick function

In [11]:
def McCormick(x):
            return math.sin(x[0]+x[1]) + (x[0]-x[1])**2 - 1.5*x[0] + 2.5*x[1] + 1

In [12]:
bounds = [(-1.5, 4), (-3, 4)]

In [20]:
result = differential_evolution(McCormick, bounds)
result.x, result.fun

(array([-0.54719738, -1.5471974 ]), -1.9132229549809936)

Third Example - Bird Function

In [37]:
def Bird(x):
            return math.sin(x[0])*np.exp((1-math.cos(x[1]))**2) + math.cos(x[1])*np.exp((1-math.sin(x[0]))**2)  + (x[0]-x[1])**2

In [44]:
bounds = [(-10, 10), (-10, 10)]

In [47]:
result = differential_evolution(Bird, bounds)
result.x, result.fun

(array([-7.8653275 , -9.41343207]), -106.76453674926444)